
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpflebtklgnivcanhlbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJwZmxlYnRrbGduaXZjYW5obGJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzODQxNTgsImV4cCI6MjA1ODk2MDE1OH0.CqYSMYAs6DZz7sT2z6B0ljqj3yMahuFcSTh0wYBnz_E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true, // Store the session in localStorage for persistence
    autoRefreshToken: true, // Automatically refresh the token when it's about to expire
    detectSessionInUrl: true, // Detect if there's a session in the URL
    storageKey: 'supabase-auth' // Key to store the session in localStorage
  }
});
